### ISSUE TITLE
[Bug] [Chrome 81+] Usage of RTCPeerConnection close causes the party to break when a player leaves.

### ISSUE THREAD

**Issue by Isaac702** [Katharine/ponytone#22]
### Summary:

Chrome 81 changed the behaviour of RTCPeerConnection close to not fire a signalingstatechange event when close is called directly. https://bugs.chromium.org/p/chromium/issues/detail?id=699036

Ponytone currently relies on this behaviour to remove a player  when they leave the game.

https://github.com/Katharine/ponytone/blob/0702367/assets/js/lib/party/p2p.ts#L130-L141
https://github.com/Katharine/ponytone/blob/0702367/assets/js/lib/party/comms.ts#L133-L136

Affected Browsers:
* Chrome 81 onwards.

### Expected Behaviour
When a player leaves the party they should be removed and the remaining players should be able to continue with their game.

### Current Behaviour
Due to the change in behaviour in Chrome when a player leaves the party their RTCPeerConnection is not removed from the rtcConnections hashTable used by the other players. This causes exceptions when messages are broadcasted and breaks the party as no additional communication can be done between the players. To fix this the players must setup a new party and join it instead.

Example Exception.
```
Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
    at e.PeerConnection.send (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:40635)
    at e.NetworkSession.broadcast (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:32830)
    at e.Party.setReady (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:31792)
    at e.GameController._handleReady (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:27739)
    at e.Ready.<anonymous> (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:25472)
    at e.Ready.n.emit (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:1364)
    at e.Ready._handleReady (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:89654)
    at HTMLButtonElement.button.onclick (https://ponytone.online/static/party-d25a40a65fe468cece0b.js:1:88492)
```

### Possible Solution
Either;
* Call 'this.emit("close")' when closing PeerConnection to re-introduce the previous behaviour. https://github.com/Katharine/ponytone/blob/0702367/assets/js/lib/party/p2p.ts#L44
* Check if the PeerConnection's signalingState is 'closed' before use and trigger it to be removed from rtcConnections.

I'm not familiar with WebRTC so I don't know which of the above is better or if there is another more appropriate solution.

**Comment by Isaac702** [comment]
I took another look at this as I wanted to understand the full scope of the problem before submitting a PR and I wanted to understand WebRTC a bit better.

When ponytone creates the RTCPeerConnection it configures it to handle "failed", "closed" and "disconnected" [iceconnectionstatechange](https://github.com/Katharine/ponytone/blob/0702367/assets/js/lib/party/p2p.ts#L127-L141) events. I didn't understand why the "disconnected" event wasn't being handled as it should also have prevented this problem.

It looks like when a player closes their web-browser or navigates away from the page the [member_left](https://github.com/Katharine/ponytone/blob/0702367/assets/js/lib/party/comms.ts#L107-L118) WebSocket message is handled first and this logic closes the RTCPeerConnection before the "disconnected" event occurs. If it isn't closed the "disconnected" event fires shortly afterwards. This is useful to know as there could be cases where the "disconnected" event can occur but "members_left" doesn't (Eg. Players losing the connection between themselves but not the connection to the Ponytone server).
